### PR TITLE
Re-wrote to work with latest Power BI visuals SDK; added latest Vega/…

### PR DESCRIPTION
**Pull request by dm-p**
…Vega-Lite packages and fixed typings for Vega spec. Removed the logger, as this hasn't worked in the SDK for a while and the team have yet to document a suitable replacement.

### CODE REVIEW

**Comment by domoritz** [comment]
That's awesome. Thanks for the update.

**Comment by domoritz** [comment]
@uve can you take a look at this pull request?

**Comment by danmarshall** [comment]
Hi @dm-p thanks for this PR! Would you mind deleting webpack.statistics.dev.html and adding it to .gitignore?

**Comment by dm-p** [comment]
Hi @danmarshall, and thanks for picking this up! I'd overlooked the .gitignore, as the v2 SDK wasn't using webpack. Have corrected and hopefully this should be okay now.

**Comment by domoritz** [comment]
Thank you @dm-p and @danmarshall!

**Pull request merged**
